/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista.gui;

import sistemaserviciotecnico.SistemaServicioTecnico;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import modelo.OrdenTrabajo;
/**
 *
 * @author cris
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    private SistemaServicioTecnico sistema;
    
    private void actualizarTablaOrdenes() {
        actualizarTablaOrdenes(sistema.listarOrdenes());
    }

    // Método sobrecargado: carga la lista que le pases (SIA-8 y SIA-9)
    private void actualizarTablaOrdenes(java.util.List<modelo.OrdenTrabajo> lista) {
        String[] columnas = {"ID", "Fecha", "RUT Cliente", "Equipo", "Estado", "Entrega"};
        javax.swing.table.DefaultTableModel modeloTabla = new javax.swing.table.DefaultTableModel(null, columnas) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; 
            }
        };

        for (modelo.OrdenTrabajo ot : lista) {
            Object[] fila = new Object[6];
            fila[0] = ot.getIdOrden();
            fila[1] = ot.getFechaRecepcion();
            fila[2] = ot.getClienteAtendido().getRut();
            fila[3] = ot.getComputadorMalo().getMarca() + " " + ot.getComputadorMalo().getModelo();
            fila[4] = ot.getEstado();
            fila[5] = ot.getFechaEntregaEstimada();
            modeloTabla.addRow(fila);
        }
        tablaOrdenes.setModel(modeloTabla);
    }
    
    private void actualizarTablaInventario() {
        String[] columnas = {"Código", "Nombre", "Precio", "Stock"};
        
        javax.swing.table.DefaultTableModel modeloTabla = new javax.swing.table.DefaultTableModel(null, columnas) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; 
            }
        };

        for (modelo.Componente c : sistema.getInventarioStock().values()) {
            Object[] fila = new Object[4];
            fila[0] = c.getCodigo();
            fila[1] = c.getNombre();
            fila[2] = c.getPrecio();
            fila[3] = c.getStock();
            modeloTabla.addRow(fila);
        }
        
        tablaInventario.setModel(modeloTabla);
    }
    
    
    public VentanaPrincipal(SistemaServicioTecnico sistema) {
        this.sistema = sistema;
        initComponents();
        actualizarTablaOrdenes();
        actualizarTablaInventario();
        setLocationRelativeTo(null);
        
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                sistema.guardarDatosSistema();
                System.out.println("Datos guardados en CSV. Cerrando intefaz gráfica...");
                System.exit(0);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaInventario = new javax.swing.JTable();
        btnNuevoRepuesto = new javax.swing.JButton();
        btnAumentarStock = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaOrdenes = new javax.swing.JTable();
        btnNuevaOrden = new javax.swing.JButton();
        btnModificarEstado = new javax.swing.JButton();
        btnEliminarOrden = new javax.swing.JButton();
        btnBuscarRut = new javax.swing.JButton();
        btnFiltrarActivas = new javax.swing.JButton();
        btnMostrarTodas = new javax.swing.JButton();
        btnAgregarRepuesto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablaInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tablaInventario);

        btnNuevoRepuesto.setText("Nuevo Repuesto");
        btnNuevoRepuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoRepuestoActionPerformed(evt);
            }
        });

        btnAumentarStock.setText("Aumentar Stock");
        btnAumentarStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAumentarStockActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnNuevoRepuesto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAumentarStock))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(238, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevoRepuesto)
                    .addComponent(btnAumentarStock))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Inventario", jPanel3);

        tablaOrdenes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Fecha Recepción", "Cliente (RUT)", "Equipo", "Estado", "Entrega Estimada"
            }
        ));
        jScrollPane1.setViewportView(tablaOrdenes);

        jScrollPane2.setViewportView(jScrollPane1);

        btnNuevaOrden.setText("Nueva Orden");
        btnNuevaOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaOrdenActionPerformed(evt);
            }
        });

        btnModificarEstado.setText("Modificar Estado");
        btnModificarEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarEstadoActionPerformed(evt);
            }
        });

        btnEliminarOrden.setText("Eliminar Orden");
        btnEliminarOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarOrdenActionPerformed(evt);
            }
        });

        btnBuscarRut.setText("Buscar RUT");
        btnBuscarRut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarRutActionPerformed(evt);
            }
        });

        btnFiltrarActivas.setText("Filtrar Activas");
        btnFiltrarActivas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarActivasActionPerformed(evt);
            }
        });

        btnMostrarTodas.setText("Limpiar Filtros");
        btnMostrarTodas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarTodasActionPerformed(evt);
            }
        });

        btnAgregarRepuesto.setText("Agregar Repuesto");
        btnAgregarRepuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarRepuestoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnBuscarRut)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFiltrarActivas)
                        .addGap(346, 346, 346)
                        .addComponent(btnMostrarTodas))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnNuevaOrden)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnModificarEstado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminarOrden)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAgregarRepuesto)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMostrarTodas, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnFiltrarActivas)
                        .addComponent(btnBuscarRut)))
                .addGap(4, 4, 4)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarRepuesto)
                    .addComponent(btnNuevaOrden)
                    .addComponent(btnModificarEstado)
                    .addComponent(btnEliminarOrden))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Órdenes", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevaOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaOrdenActionPerformed
        // TODO add your handling code here:
        javax.swing.JTextField txtId = new javax.swing.JTextField();
        javax.swing.JTextField txtRut = new javax.swing.JTextField();
        javax.swing.JTextField txtNombre = new javax.swing.JTextField();
        javax.swing.JTextField txtTelefono = new javax.swing.JTextField();
        javax.swing.JTextField txtEmail = new javax.swing.JTextField();
        javax.swing.JTextField txtMarca = new javax.swing.JTextField();
        javax.swing.JTextField txtModelo = new javax.swing.JTextField();
        javax.swing.JTextField txtProblema = new javax.swing.JTextField();
        javax.swing.JTextField txtAnio = new javax.swing.JTextField();

        // Se agregan ToolTips (texto de ayuda al posar el cursor sobre la casilla)
        txtRut.setToolTipText("Formato esperado: 12345678-9");
        txtTelefono.setToolTipText("Ejemplo: 987654321");
        txtAnio.setToolTipText("Ejemplo: 2023");

        // Se integran los ejemplos visuales directamente en el texto del label
        Object[] mensaje = {
            "ID Orden (ej: 105):", txtId,
            "RUT Cliente (ej: 12345678-9):", txtRut,
            "Nombre Cliente:", txtNombre,
            "Teléfono (ej: 987654321):", txtTelefono,
            "Email:", txtEmail,
            "Marca PC:", txtMarca,
            "Modelo PC:", txtModelo,
            "Problema reportado:", txtProblema,
            "Año PC (ej: 2022):", txtAnio
        };

        boolean ordenCreada = false;

        // Bucle de control: se repite hasta que los datos sean válidos o el usuario cancele
        while (!ordenCreada) {
            int opcion = javax.swing.JOptionPane.showConfirmDialog(this, mensaje, "Registrar Nueva Orden", javax.swing.JOptionPane.OK_CANCEL_OPTION);
            
            if (opcion == javax.swing.JOptionPane.OK_OPTION) {
                try {
                    // Pre-validación para evitar procesamiento de datos en blanco
                    if (txtId.getText().trim().isEmpty() || txtRut.getText().trim().isEmpty()) {
                        javax.swing.JOptionPane.showMessageDialog(this, "Los campos ID y RUT son obligatorios.", "Advertencia de integridad", javax.swing.JOptionPane.WARNING_MESSAGE);
                        continue; // Salta a la siguiente iteración del while, manteniendo la ventana
                    }

                    // Parseo estricto
                    int id = Integer.parseInt(txtId.getText().trim());
                    int telefono = Integer.parseInt(txtTelefono.getText().trim());
                    short anio = Short.parseShort(txtAnio.getText().trim());

                    modelo.Cliente cliente = new modelo.Cliente(txtRut.getText().trim(), txtNombre.getText().trim(), telefono, txtEmail.getText().trim());
                    modelo.Computador pc = new modelo.Computador(txtMarca.getText().trim(), txtModelo.getText().trim(), txtProblema.getText().trim(), anio);
                    modelo.OrdenTrabajo orden = new modelo.OrdenTrabajo(id, java.time.LocalDate.now().toString(), txtProblema.getText().trim(), "", "RECIBIDO", cliente, pc);

                    sistema.agregarOrden(orden);
                    actualizarTablaOrdenes();
                    
                    javax.swing.JOptionPane.showMessageDialog(this, "Orden registrada en el sistema.");
                    ordenCreada = true; // Finaliza el bucle
                    
                } catch (NumberFormatException e) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Error de tipo de dato: ID, Teléfono y Año requieren valores numéricos exclusivamente.\nRevise sus ingresos.", "Fallo de validación", javax.swing.JOptionPane.ERROR_MESSAGE);
                    // Al no cambiar 'ordenCreada' a true, el while se repite y recarga las variables intactas
                }
            } else {
                // Condición de salida si se presiona Cancelar o la X
                break;
            }
        }
    }//GEN-LAST:event_btnNuevaOrdenActionPerformed

    private void btnModificarEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarEstadoActionPerformed
        // TODO add your handling code here:
        int filaSeleccionada = tablaOrdenes.getSelectedRow();
        
        if (filaSeleccionada == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Debe seleccionar una orden de la tabla primero.", "Advertencia", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Obtener el ID de la columna 0 de la fila seleccionada
        int idOrden = (int) tablaOrdenes.getValueAt(filaSeleccionada, 0);
        
        String[] opciones = {"EN_REPARACION", "LISTO", "ENTREGADO"};
        String nuevoEstado = (String) javax.swing.JOptionPane.showInputDialog(this, "Seleccione el nuevo estado:", "Modificar Estado", javax.swing.JOptionPane.QUESTION_MESSAGE, null, opciones, opciones[0]);

        if (nuevoEstado != null) {
            try {
                sistema.actualizarEstadoOrden(idOrden, nuevoEstado);
                actualizarTablaOrdenes();
            } catch (excepciones.OrdenNoEncontradaException ex) {
                javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnModificarEstadoActionPerformed

    private void btnEliminarOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarOrdenActionPerformed
        // TODO add your handling code here:
        int filaSeleccionada = tablaOrdenes.getSelectedRow();
        
        if (filaSeleccionada == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Debe seleccionar una orden de la tabla primero.", "Advertencia", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        int idOrden = (int) tablaOrdenes.getValueAt(filaSeleccionada, 0);
        
        int confirmacion = javax.swing.JOptionPane.showConfirmDialog(this, "¿Está seguro de que desea eliminar la orden " + idOrden + "?", "Confirmar Eliminación", javax.swing.JOptionPane.YES_NO_OPTION);
        
        if (confirmacion == javax.swing.JOptionPane.YES_OPTION) {
            try {
                sistema.eliminarOrden(idOrden);
                actualizarTablaOrdenes();
            } catch (excepciones.OrdenNoEncontradaException ex) {
                javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnEliminarOrdenActionPerformed

    private void btnBuscarRutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarRutActionPerformed
        // TODO add your handling code here:
        String rut = javax.swing.JOptionPane.showInputDialog(this, "Ingrese RUT a buscar:");
        
        if (rut != null && !rut.trim().isEmpty()) {
            java.util.List<modelo.OrdenTrabajo> resultados = sistema.buscarOrden(rut.trim());
            if (resultados.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "No se encontraron órdenes para ese RUT.");
                actualizarTablaOrdenes(); // Restaura la tabla completa
            } else {
                actualizarTablaOrdenes(resultados); // Muestra solo los resultados
            }
        }
    }//GEN-LAST:event_btnBuscarRutActionPerformed

    private void btnFiltrarActivasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarActivasActionPerformed
        // TODO add your handling code here:
        java.util.List<modelo.OrdenTrabajo> activas = sistema.filtrarOrdenesActivas();
        actualizarTablaOrdenes(activas);
    }//GEN-LAST:event_btnFiltrarActivasActionPerformed

    private void btnMostrarTodasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarTodasActionPerformed
        // TODO add your handling code here:
        actualizarTablaOrdenes();
    }//GEN-LAST:event_btnMostrarTodasActionPerformed

    private void btnAgregarRepuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarRepuestoActionPerformed
        // TODO add your handling code here:
        int filaSeleccionada = tablaOrdenes.getSelectedRow();
        
        if (filaSeleccionada == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Debe seleccionar una orden de la tabla primero.", "Advertencia", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        int idOrden = (int) tablaOrdenes.getValueAt(filaSeleccionada, 0);
        
        String codPieza = javax.swing.JOptionPane.showInputDialog(this, "Ingrese el código del repuesto (ej: RAM-16):");
        if (codPieza == null || codPieza.trim().isEmpty()) return;

        try {
            String cantStr = javax.swing.JOptionPane.showInputDialog(this, "Cantidad a utilizar:");
            if (cantStr == null || cantStr.trim().isEmpty()) return;
            
            int cant = Integer.parseInt(cantStr.trim());

            // SIA-12: Captura de excepciones personalizadas
            sistema.agregarComponenteAOrden(idOrden, codPieza.trim(), cant);
            actualizarTablaOrdenes(); // Actualiza para reflejar posible cambio en fecha de entrega
            
            javax.swing.JOptionPane.showMessageDialog(this, "Repuesto asignado y stock descontado exitosamente.");
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "La cantidad debe ser un número entero.", "Error de formato", javax.swing.JOptionPane.ERROR_MESSAGE);
        } catch (excepciones.OrdenNoEncontradaException | excepciones.StockInsuficienteException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, ex.getMessage(), "Error de negocio", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAgregarRepuestoActionPerformed

    private void btnNuevoRepuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoRepuestoActionPerformed
        // TODO add your handling code here:
        String codigo = javax.swing.JOptionPane.showInputDialog(this, "Código del nuevo repuesto (ej: SSD-2TB):");
        if (codigo == null || codigo.trim().isEmpty()) return;

        // Validación de clave única en el HashMap
        if (sistema.getInventarioStock().containsKey(codigo.trim())) {
            javax.swing.JOptionPane.showMessageDialog(this, "El código ingresado ya existe en el inventario.", "Clave duplicada", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        String nombre = javax.swing.JOptionPane.showInputDialog(this, "Nombre o descripción del componente:");
        if (nombre == null || nombre.trim().isEmpty()) return;

        try {
            String precioStr = javax.swing.JOptionPane.showInputDialog(this, "Precio unitario:");
            if (precioStr == null || precioStr.trim().isEmpty()) return;
            double precio = Double.parseDouble(precioStr.trim());

            String stockStr = javax.swing.JOptionPane.showInputDialog(this, "Stock inicial:");
            if (stockStr == null || stockStr.trim().isEmpty()) return;
            int stock = Integer.parseInt(stockStr.trim());

            // Instancia y almacenamiento en la colección secundaria
            modelo.Componente nuevo = new modelo.Componente(codigo.trim(), nombre.trim(), precio, stock);
            sistema.getInventarioStock().put(nuevo.getCodigo(), nuevo);
            
            actualizarTablaInventario();
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Fallo de validación: Precio y Stock deben ser numéricos.", "Error de formato", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnNuevoRepuestoActionPerformed

    private void btnAumentarStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAumentarStockActionPerformed
        // TODO add your handling code here:
        int filaSeleccionada = tablaInventario.getSelectedRow();
        
        if (filaSeleccionada == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Debe seleccionar un repuesto de la tabla de inventario primero.", "Advertencia", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Recupera la clave (Código) desde la columna 0 de la tabla
        String codigo = (String) tablaInventario.getValueAt(filaSeleccionada, 0);
        modelo.Componente comp = sistema.getInventarioStock().get(codigo);

        try {
            String cantStr = javax.swing.JOptionPane.showInputDialog(this, "Ingrese la cantidad de unidades a sumar al stock actual (" + comp.getStock() + "):");
            if (cantStr == null || cantStr.trim().isEmpty()) return;
            
            int cantidadAgregar = Integer.parseInt(cantStr.trim());
            if (cantidadAgregar < 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Operación inválida: No se pueden ingresar valores negativos.", "Error lógico", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Edita el estado del objeto en memoria
            comp.setStock(comp.getStock() + cantidadAgregar);
            actualizarTablaInventario();
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Fallo de validación: Debe ingresar un número entero.", "Error de formato", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAumentarStockActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarRepuesto;
    private javax.swing.JButton btnAumentarStock;
    private javax.swing.JButton btnBuscarRut;
    private javax.swing.JButton btnEliminarOrden;
    private javax.swing.JButton btnFiltrarActivas;
    private javax.swing.JButton btnModificarEstado;
    private javax.swing.JButton btnMostrarTodas;
    private javax.swing.JButton btnNuevaOrden;
    private javax.swing.JButton btnNuevoRepuesto;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable tablaInventario;
    private javax.swing.JTable tablaOrdenes;
    // End of variables declaration//GEN-END:variables
}
